// Real Sam Network Solutions data
window.SAM_DATA = {
  brand: {
    name: 'Sam Network Solutions',
    short: 'Sam Network',
    tagline: 'Solutions IT pour entreprises',
    phone: '09 75 52 97 43',
    phoneRaw: '+33975529743',
    email: 'contact@samnetworksolutions.fr',
    address: '43 rue Froidevaux, 75014 Paris',
    hours: '7 jours sur 7 · 8h–20h',
    founder: 'Samuel',
  },
  services: [
    { id: 'reseau', icon: '◇', title: 'Équipements réseau', desc: 'Routeurs, switches, points d\'accès Wi-Fi pro. Conception et déploiement adaptés à votre activité.', features: ['Audit & dimensionnement', 'Wi-Fi maillé', 'Switches managés', 'VPN sécurisé'] },
    { id: 'voip', icon: '○', title: 'Téléphonie VOIP', desc: 'Standard téléphonique IP, postes fixes, mobiles, intégration CRM. Réduisez vos factures télécom.', features: ['IPBX cloud / sur site', 'SVI personnalisable', 'Numéros illimités', 'Intégration CRM'] },
    { id: 'video', icon: '□', title: 'Vidéosurveillance', desc: 'Caméras IP, enregistreurs, accès distant sécurisé. Conformité RGPD assurée.', features: ['Caméras 4K / IP', 'Enregistrement NVR', 'Accès mobile sécurisé', 'Conformité RGPD'] },
    { id: 'securite', icon: '△', title: 'Sécurité informatique', desc: 'Pare-feu, antivirus, sauvegarde, chiffrement. Protégez vos données contre rançongiciels et intrusions.', features: ['Firewall pro', 'Antivirus centralisé', 'Sauvegarde 3-2-1', 'Audit pentest'] },
    { id: 'depannage', icon: '×', title: 'Dépannage IT', desc: 'Intervention sur site sous 4h ouvrées à Paris et IDF. Diagnostic, réparation, urgences 7j/7.', features: ['Intervention < 4h', '7j/7 disponible', 'Diagnostic offert', 'Devis gratuit'] },
    { id: 'maintenance', icon: '◎', title: 'Contrats de maintenance', desc: 'Forfaits préventifs et correctifs. Helpdesk, supervision proactive, mises à jour planifiées.', features: ['Forfaits adaptés', 'Helpdesk dédié', 'Supervision 24/7', 'SLA contractuels'] },
    { id: 'materiel', icon: '▢', title: 'Vente de matériel', desc: 'PC pro, serveurs, périphériques, consommables. Conseil, fourniture et installation.', features: ['Marques certifiées', 'Conseil sur mesure', 'Installation incluse', 'Garantie étendue'] },
    { id: 'photocopie', icon: '◫', title: 'Photocopieurs & impression', desc: 'Multifonctions A3/A4, gestion documentaire, impression sécurisée. Location et achat.', features: ['MFP A3 / A4', 'Print sécurisé', 'Suivi des coûts', 'SAV inclus'] },
  ],
  stats: [
    { v: '89+', k: 'avis Google', sub: 'Note 4,9/5' },
    { v: '< 4h', k: 'intervention', sub: 'À Paris & IDF' },
    { v: '7j/7', k: 'disponibilité', sub: 'Astreinte téléphonique' },
    { v: '10 ans+', k: 'd\'expertise', sub: 'Au service des PME' },
  ],
  process: [
    { n: '01', title: 'Audit gratuit', desc: 'Visite sur site, état des lieux de votre infrastructure. Sans engagement.' },
    { n: '02', title: 'Préconisations', desc: 'Devis transparent, planning d\'intervention, choix des équipements adaptés à votre budget.' },
    { n: '03', title: 'Mise en œuvre', desc: 'Installation par nos techniciens certifiés, formation des équipes, mise en production progressive.' },
    { n: '04', title: 'Suivi & maintenance', desc: 'Supervision continue, helpdesk réactif, évolutions accompagnées dans la durée.' },
  ],
  testimonials: [
    { quote: 'Un service au top. Souriant, pédagogue, une réactivité incroyable. Il a pu me dépanner dans la journée. Merci Sam, je recommande vivement.', author: 'Felix Labeau', role: 'Avis Google', stars: 5 },
    { quote: 'Sam est un professionnel de confiance, très réactif, et qui saura apporter des solutions adaptées à vos demandes ! Je recommande vivement !', author: 'Axel Descourvieres', role: 'Avis Google', stars: 5 },
    { quote: 'Meilleur réparateur et prestataire de service IT du quartier ! Sam peut faire absolument tout sur demande, et en plus il est super sympa !! Je recommande :)', author: 'Subtherion', role: 'Avis Google', stars: 5 },
    { quote: 'Excellent service! Samie is smart, efficient, fast and precise. He understood exactly what was needed for my MacBook battery, found the right one, and made sure it worked before pickup. Highly recommend!', author: 'Matthew Rose', role: 'Avis Google', stars: 5 },
    { quote: 'Très bien accueilli, café disponible et très professionnel. Gentil patron et personnel.', author: 'Jean-Luc Dubois', role: 'Avis Google', stars: 5 },
    { quote: 'Superbe expérience avec Sam et ses collègues. Très bons conseils.', author: 'Estelle Simoneton', role: 'Avis Google', stars: 5 },
    { quote: 'Super réparation de mon PC, rapide et efficace.', author: 'Bérénice Frereau', role: 'Avis Google', stars: 5 },
    { quote: 'Boutique informatique extraordinaire. Je vous recommande vivement.', author: 'Xavier Fremont', role: 'Avis Google', stars: 5 },
    { quote: 'Intervention rapide, équipe professionnelle. Notre réseau Wi-Fi est enfin stable dans tout le bâtiment.', author: 'Cabinet d\'avocats', role: 'Paris 8e', stars: 5 },
  ],
  faqs: [
    { q: 'Intervenez-vous en dehors de Paris ?', a: 'Oui, nous couvrons toute l\'Île-de-France. Pour les départements limitrophes, contactez-nous pour devis.' },
    { q: 'Quels sont vos délais d\'intervention ?', a: 'Sous 4 heures ouvrées à Paris et petite couronne pour les contrats de maintenance. Sous 24h pour les nouveaux clients.' },
    { q: 'Travaillez-vous avec des particuliers ?', a: 'Notre cœur de métier sont les TPE/PME, mais nous intervenons aussi pour les particuliers exigeants (résidence, télétravail).' },
    { q: 'Proposez-vous des contrats sur mesure ?', a: 'Tous nos contrats sont adaptés à votre infrastructure et à votre budget. Audit préalable systématique.' },
    { q: 'Êtes-vous assurés ?', a: 'Oui, responsabilité civile professionnelle complète. Documents transmis sur demande.' },
    { q: 'Quels sont vos tarifs ?', a: 'À partir de 89 €HT/h pour le dépannage, forfaits maintenance dès 290 €HT/mois. Devis gratuit en 24h.' },
  ],
};
