// Real Sam Network Solutions data
window.SAM_DATA = {
  brand: {
    name: 'Sam Network Solutions',
    short: 'Sam Network',
    tagline: 'Solutions IT pour entreprises',
    phone: '09 75 52 97 43',
    phoneRaw: '+33975529743',
    email: 'contact@samnetworksolutions.fr',
    address: '43 rue Froidevaux, 75014 Paris',
    hours: '7 jours sur 7 · 8h–20h',
    founder: 'Samuel',
  },
  services: [
    {
      id: 'reseaux', icon: '◇', title: 'Réseaux Informatique & Baie de Brassage',
      desc: 'Conception, installation et configuration de votre infrastructure réseau et baies de brassage.',
      longDesc: "Une infrastructure réseau bien pensée, c'est la colonne vertébrale invisible qui fait tourner votre entreprise. Nous concevons, câblons et configurons des réseaux fiables, évolutifs et sécurisés — du simple bureau au site multi-étages. Baies de brassage propres, étiquetées, documentées : fini les armoires en spaghetti.",
      features: ['Câblage structuré cat. 6/6a/7', 'Baie de brassage organisée', 'Switches & routeurs pro', 'Wi-Fi pro multi-bornes'],
      image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1400&q=85&auto=format&fit=crop',
    },
    {
      id: 'infogerance', icon: '◎', title: 'Infogérance Informatique',
      desc: 'Supervision et gestion complète de votre parc informatique pour assurer la continuité de votre activité.',
      longDesc: "Concentrez-vous sur votre métier, on s'occupe du reste. Supervision proactive 24/7, mises à jour automatisées, helpdesk réactif, sauvegardes pilotées : votre parc est sous contrôle. Vous appelez un seul numéro, vous payez un forfait clair, vous dormez tranquille.",
      features: ['Supervision 24/7 proactive', 'Mises à jour & patchs', 'Helpdesk illimité', 'Sauvegarde & restauration'],
      image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1400&q=85&auto=format&fit=crop',
    },
    {
      id: 'cyber', icon: '△', title: 'Cyber Sécurité',
      desc: 'Protection de vos données et de votre réseau contre les menaces numériques et intrusions.',
      longDesc: "Une attaque coûte en moyenne 400 000€ à une PME. La cybersécurité n'est plus optionnelle. On audite votre exposition, on déploie pare-feu nouvelle génération, antivirus EDR et politiques d'accès, on forme vos équipes au phishing. Mieux vaut prévenir que rançonner.",
      features: ['Pare-feu nouvelle génération', 'Antivirus EDR', 'Audit de sécurité complet', 'Protection ransomware'],
      image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1400&q=85&auto=format&fit=crop',
    },
    {
      id: 'video', icon: '□', title: 'Vidéosurveillance',
      desc: 'Systèmes de vidéosurveillance haute définition pour sécuriser vos locaux 24h/24 et 7j/7.',
      longDesc: "Caméras 4K, vision nocturne, intelligence artificielle de détection — la vidéosurveillance moderne est un outil dissuasif et probant. Consultation à distance depuis smartphone, archivage sécurisé, conformité RGPD garantie. On installe, on configure, on forme.",
      features: ['Caméras IP 4K & vision nuit', 'Enregistreur NVR sécurisé', 'Consultation mobile à distance', 'Conformité RGPD intégrée'],
      image: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=1400&q=85&auto=format&fit=crop',
    },
    {
      id: 'acces', icon: '◫', title: "Contrôle d'Accès & Alarme Intrusion",
      desc: "Sécurisez les accès à vos bâtiments et protégez-vous contre les effractions.",
      longDesc: "Qui rentre, quand, et avec quel droit ? Badges, codes, biométrie : maîtrisez chaque accès depuis une interface unique. Couplé à une alarme anti-intrusion télésurveillée, votre bâtiment est protégé 24/7 — avec intervention en cas d'alerte.",
      features: ['Badges, codes & biométrie', 'Gestion centralisée des accès', 'Alarme anti-intrusion', 'Télésurveillance 24/7'],
      image: 'https://images.unsplash.com/photo-1622037022824-0c71d511ef3c?w=1400&q=85&auto=format&fit=crop',
    },
    {
      id: 'depannage', icon: '×', title: 'Dépannage & Maintenance Informatique',
      desc: 'Intervention rapide sur site ou à distance pour résoudre toutes vos pannes informatiques.',
      longDesc: "Quand ça casse, vous appelez. On intervient sous 4h ouvrées en région parisienne — souvent dans la journée. Diagnostic précis, devis transparent, réparation propre. Pour éviter le sinistre, prenez un contrat de maintenance : on prévient au lieu de guérir.",
      features: ['Intervention sous 4h', 'Diagnostic précis & transparent', 'Réparation matérielle & logicielle', 'Contrats de maintenance flexibles'],
      image: 'https://images.unsplash.com/photo-1597733336794-12d05021d510?w=1400&q=85&auto=format&fit=crop',
    },
  ],
  stats: [
    { v: '89+', k: 'avis Google', sub: 'Note 4,9/5' },
    { v: '< 4h', k: 'intervention', sub: 'À Paris & IDF' },
    { v: '7j/7', k: 'disponibilité', sub: 'Astreinte téléphonique' },
    { v: '10 ans+', k: 'd\'expertise', sub: 'Au service des PME' },
  ],
  process: [
    { n: '01', title: 'Audit gratuit', desc: 'Visite sur site, état des lieux de votre infrastructure. Sans engagement.' },
    { n: '02', title: 'Préconisations', desc: 'Devis transparent, planning d\'intervention, choix des équipements adaptés à votre budget.' },
    { n: '03', title: 'Mise en œuvre', desc: 'Installation par nos techniciens certifiés, formation des équipes, mise en production progressive.' },
    { n: '04', title: 'Suivi & maintenance', desc: 'Supervision continue, helpdesk réactif, évolutions accompagnées dans la durée.' },
  ],
  testimonials: [
    { quote: 'Un service au top. Souriant, pédagogue, une réactivité incroyable. Il a pu me dépanner dans la journée. Merci Sam, je recommande vivement.', author: 'Felix Labeau', role: 'Avis Google', stars: 5 },
    { quote: 'Sam est un professionnel de confiance, très réactif, et qui saura apporter des solutions adaptées à vos demandes ! Je recommande vivement !', author: 'Axel Descourvieres', role: 'Avis Google', stars: 5 },
    { quote: 'Meilleur réparateur et prestataire de service IT du quartier ! Sam peut faire absolument tout sur demande, et en plus il est super sympa !! Je recommande :)', author: 'Subtherion', role: 'Avis Google', stars: 5 },
    { quote: 'Excellent service! Samie is smart, efficient, fast and precise. He understood exactly what was needed for my MacBook battery, found the right one, and made sure it worked before pickup. Highly recommend!', author: 'Matthew Rose', role: 'Avis Google', stars: 5 },
    { quote: 'Très bien accueilli, café disponible et très professionnel. Gentil patron et personnel.', author: 'Jean-Luc Dubois', role: 'Avis Google', stars: 5 },
    { quote: 'Superbe expérience avec Sam et ses collègues. Très bons conseils.', author: 'Estelle Simoneton', role: 'Avis Google', stars: 5 },
    { quote: 'Super réparation de mon PC, rapide et efficace.', author: 'Bérénice Frereau', role: 'Avis Google', stars: 5 },
    { quote: 'Boutique informatique extraordinaire. Je vous recommande vivement.', author: 'Xavier Fremont', role: 'Avis Google', stars: 5 },
    { quote: 'Intervention rapide, équipe professionnelle. Notre réseau Wi-Fi est enfin stable dans tout le bâtiment.', author: 'Cabinet d\'avocats', role: 'Paris 8e', stars: 5 },
  ],
  faqs: [
    { q: 'Intervenez-vous en dehors de Paris ?', a: 'Oui, nous couvrons toute l\'Île-de-France. Pour les départements limitrophes, contactez-nous pour devis.' },
    { q: 'Quels sont vos délais d\'intervention ?', a: 'Sous 4 heures ouvrées à Paris et petite couronne pour les contrats de maintenance. Sous 24h pour les nouveaux clients.' },
    { q: 'Travaillez-vous avec des particuliers ?', a: 'Notre cœur de métier sont les TPE/PME, mais nous intervenons aussi pour les particuliers exigeants (résidence, télétravail).' },
    { q: 'Proposez-vous des contrats sur mesure ?', a: 'Tous nos contrats sont adaptés à votre infrastructure et à votre budget. Audit préalable systématique.' },
    { q: 'Êtes-vous assurés ?', a: 'Oui, responsabilité civile professionnelle complète. Documents transmis sur demande.' },
    { q: 'Quels sont vos tarifs ?', a: 'À partir de 89 €HT/h pour le dépannage, forfaits maintenance dès 290 €HT/mois. Devis gratuit en 24h.' },
  ],
};
